-- Generated by Oracle SQL Developer Data Modeler 24.3.1.351.0831
--   at:        2025-06-06 20:58:20 WIB
--   site:      SQL Server 2012
--   type:      SQL Server 2012

-- Disesuaikan untuk PostgreSQL
--Tabahan fitur



CREATE TABLE Absensi
    (
     absensi_id SERIAL PRIMARY KEY , -- Diubah menjadi SERIAL PRIMARY KEY
     tanggal TIMESTAMP NOT NULL ,
     status VARCHAR(50) NOT NULL ,
     Users_user_id VARCHAR (7) NOT NULL ,
     Jadwal_jadwal_id SERIAL NOT NULL -- Diubah menjadi SERIAL (asumsi Jadwal_jadwal_id juga bisa auto-increment)
    );

-- ALTER TABLE Absensi ADD CONSTRAINT Absensi_PK PRIMARY KEY (absensi_id); -- Sudah termasuk dalam SERIAL PRIMARY KEY

CREATE TABLE Detail_Pengajar
    (
     Users_user_id VARCHAR (7) NOT NULL ,
     Kelas_Users_user_id VARCHAR (7) NOT NULL ,
     Matpel_mapel_id SERIAL NOT NULL , -- Diubah menjadi SERIAL
     Kelas_kelas_id SERIAL NOT NULL -- Diubah menjadi SERIAL
    );

CREATE TABLE Feedback
    (
     feedback_id SERIAL PRIMARY KEY , -- Diubah menjadi SERIAL PRIMARY KEY
     feedback VARCHAR(255) NOT NULL ,
     Users_user_id VARCHAR (7) NOT NULL
    );

-- ALTER TABLE Feedback ADD CONSTRAINT Feedback_PK PRIMARY KEY (feedback_id); -- Sudah termasuk dalam SERIAL PRIMARY KEY

CREATE TABLE Jadwal
    (
     jadwal_id SERIAL PRIMARY KEY , -- Diubah menjadi SERIAL PRIMARY KEY
     hari VARCHAR(20) NOT NULL ,
     jam_mulai VARCHAR(10) NOT NULL ,
     jam_selsai VARCHAR(10) NOT NULL ,
     Kelas_Users_user_id VARCHAR (7) NOT NULL ,
     Matpel_mapel_id SERIAL NOT NULL , -- Diubah menjadi SERIAL
     Kelas_kelas_id SERIAL NOT NULL -- Diubah menjadi SERIAL
    );

-- ALTER TABLE Jadwal ADD CONSTRAINT Jadwal_PK PRIMARY KEY (jadwal_id); -- Sudah termasuk dalam SERIAL PRIMARY KEY

CREATE TABLE Kelas
    (
     kelas_id SERIAL NOT NULL , -- Diubah menjadi SERIAL
     nama_kelas VARCHAR(100) NOT NULL ,
     keterangan VARCHAR(255) NOT NULL ,
     Users_user_id VARCHAR (7) NOT NULL ,
     Semester_semester_id SERIAL NOT NULL -- Diubah menjadi SERIAL
    );

ALTER TABLE Kelas ADD CONSTRAINT Kelas_PK PRIMARY KEY (Users_user_id, kelas_id);

CREATE TABLE Materi
    (
     materi_id SERIAL PRIMARY KEY , -- Diubah menjadi SERIAL PRIMARY KEY
     nama_materi VARCHAR(255) NOT NULL ,
     Kelas_Users_user_id VARCHAR (7) NOT NULL ,
     Matpel_mapel_id SERIAL NOT NULL , -- Diubah menjadi SERIAL
     Kelas_kelas_id SERIAL NOT NULL -- Diubah menjadi SERIAL
    );

-- ALTER TABLE Materi ADD CONSTRAINT Materi_PK PRIMARY KEY (materi_id); -- Sudah termasuk dalam SERIAL PRIMARY KEY

CREATE TABLE Matpel
    (
     mapel_id SERIAL PRIMARY KEY , -- Diubah menjadi SERIAL PRIMARY KEY
     nama_mapel VARCHAR(100) NOT NULL ,
     category VARCHAR(50) NOT NULL
    );

-- ALTER TABLE Matpel ADD CONSTRAINT Matpel_PK PRIMARY KEY (mapel_id); -- Sudah termasuk dalam SERIAL PRIMARY KEY

CREATE TABLE Nilai
    (
     nilai_id SERIAL PRIMARY KEY , -- Diubah menjadi SERIAL PRIMARY KEY
     nilai BIGINT NOT NULL ,
     jenis_nilai VARCHAR(50) NOT NULL ,
     Matpel_mapel_id SERIAL NOT NULL , -- Diubah menjadi SERIAL
     Rapor_rapor_id SERIAL NOT NULL -- Diubah menjadi SERIAL
    );

-- ALTER TABLE Nilai ADD CONSTRAINT Nilai_PK PRIMARY KEY (nilai_id); -- Sudah termasuk dalam SERIAL PRIMARY KEY

CREATE TABLE Pengumuman
    (
     pengumuman_id SERIAL PRIMARY KEY , -- Diubah menjadi SERIAL PRIMARY KEY
     pengumuman VARCHAR(255) NOT NULL ,
     Users_user_id VARCHAR (7) NOT NULL
    );

-- ALTER TABLE Pengumuman ADD CONSTRAINT Pengumuman_PK PRIMARY KEY (pengumuman_id); -- Sudah termasuk dalam SERIAL PRIMARY KEY

CREATE TABLE Rapor
    (
     rapor_id SERIAL PRIMARY KEY , -- Diubah menjadi SERIAL PRIMARY KEY
     Users_user_id VARCHAR (7) NOT NULL ,
     Semester_semester_id SERIAL NOT NULL -- Diubah menjadi SERIAL
    );

-- ALTER TABLE Rapor ADD CONSTRAINT Rapor_PK PRIMARY KEY (rapor_id); -- Sudah termasuk dalam SERIAL PRIMARY KEY

CREATE TABLE Role
    (
     role_id VARCHAR(1) NOT NULL , -- Tetap VARCHAR
     role_name VARCHAR(50) NOT NULL
    );

ALTER TABLE Role ADD CONSTRAINT Role_PK PRIMARY KEY (role_id);

CREATE TABLE Semester
    (
     semester_id SERIAL PRIMARY KEY , -- Diubah menjadi SERIAL PRIMARY KEY
     tahun_ajaran VARCHAR(20) NOT NULL ,
     semester VARCHAR(20) NOT NULL ,
     tahun TIMESTAMP NOT NULL
    );

-- ALTER TABLE Semester ADD CONSTRAINT Semester_PK PRIMARY KEY (semester_id); -- Sudah termasuk dalam SERIAL PRIMARY KEY

CREATE TABLE Tugas
    (
     tugas_id SERIAL PRIMARY KEY , -- Diubah menjadi SERIAL PRIMARY KEY
     keterangan VARCHAR(255) NOT NULL ,
     deadline TIMESTAMP NOT NULL ,
     tanggal_direlease TIMESTAMP NOT NULL ,
     Kelas_Users_user_id VARCHAR (7) NOT NULL ,
     Matpel_mapel_id SERIAL NOT NULL , -- Diubah menjadi SERIAL
     Kelas_kelas_id SERIAL NOT NULL -- Diubah menjadi SERIAL
    );

-- ALTER TABLE Tugas ADD CONSTRAINT Tugas_PK PRIMARY KEY (tugas_id); -- Sudah termasuk dalam SERIAL PRIMARY KEY

CREATE TABLE Ujian
    (
     ujian_id SERIAL PRIMARY KEY , -- Diubah menjadi SERIAL PRIMARY KEY
     jenis_ujian VARCHAR(50) NOT NULL ,
     tanggal TIMESTAMP NOT NULL ,
     Kelas_Users_user_id VARCHAR (7) NOT NULL ,
     Matpel_mapel_id SERIAL NOT NULL , -- Diubah menjadi SERIAL
     Kelas_kelas_id SERIAL NOT NULL -- Diubah menjadi SERIAL
    );

-- ALTER TABLE Ujian ADD CONSTRAINT Ujian_PK PRIMARY KEY (ujian_id); -- Sudah termasuk dalam SERIAL PRIMARY KEY

CREATE TABLE Users
    (
     user_id VARCHAR (7) NOT NULL , -- Tetap VARCHAR
     username VARCHAR(100) NOT NULL ,
     password VARCHAR(200) NOT NULL ,
     NIS_NIP VARCHAR(50) NOT NULL ,
     nama VARCHAR(100) NOT NULL ,
     gender VARCHAR(1) NOT NULL ,
     alamat VARCHAR(255) NOT NULL ,
     email VARCHAR(100) NOT NULL ,
     nomer_hp VARCHAR(20) NOT NULL ,
     Role_role_id VARCHAR(50) NOT NULL
    );

ALTER TABLE Users ADD CONSTRAINT Users_PK PRIMARY KEY (user_id);

CREATE TABLE User_Log
    (
     userlog_id SERIAL PRIMARY KEY , -- Diubah menjadi SERIAL PRIMARY KEY
     jenis VARCHAR(50) NOT NULL ,
     keterangan VARCHAR(255) NOT NULL ,
     waktu TIMESTAMP NOT NULL ,
     Users_user_id VARCHAR (7) NOT NULL
    );

-- ALTER TABLE User_Log ADD CONSTRAINT User_Log_PK PRIMARY KEY (userlog_id); -- Sudah termasuk dalam SERIAL PRIMARY KEY

-- NEW TABLE: Student_Class_Enrollment
CREATE TABLE Student_Class_Enrollment
    (
     Users_user_id VARCHAR (7) NOT NULL ,
     Kelas_kelas_id SERIAL NOT NULL ,
     Kelas_Users_user_id VARCHAR (7) NOT NULL
    );

ALTER TABLE Student_Class_Enrollment ADD CONSTRAINT Student_Class_Enrollment_PK PRIMARY KEY (Users_user_id, Kelas_kelas_id, Kelas_Users_user_id);


ALTER TABLE Absensi
    ADD CONSTRAINT Absensi_Jadwal_FK FOREIGN KEY
    (
     Jadwal_jadwal_id
    )
    REFERENCES Jadwal
    (
     jadwal_id
    )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION;

ALTER TABLE Absensi
    ADD CONSTRAINT Absensi_Users_FK FOREIGN KEY
    (
     Users_user_id
    )
    REFERENCES Users
    (
     user_id
    )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION;

ALTER TABLE Detail_Pengajar
    ADD CONSTRAINT Detail_Pengajar_Kelas_FK FOREIGN KEY
    (
     Kelas_Users_user_id,
     Kelas_kelas_id
    )
    REFERENCES Kelas
    (
     Users_user_id ,
     kelas_id
    )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION;

ALTER TABLE Detail_Pengajar
    ADD CONSTRAINT Detail_Pengajar_Matpel_FK FOREIGN KEY
    (
     Matpel_mapel_id
    )
    REFERENCES Matpel
    (
     mapel_id
    )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION;

ALTER TABLE Detail_Pengajar
    ADD CONSTRAINT Detail_Pengajar_Users_FK FOREIGN KEY
    (
     Users_user_id
    )
    REFERENCES Users
    (
     user_id
    )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION;

ALTER TABLE Feedback
    ADD CONSTRAINT Feedback_Users_FK FOREIGN KEY
    (
     Users_user_id
    )
    REFERENCES Users
    (
     user_id
    )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION;

ALTER TABLE Jadwal
    ADD CONSTRAINT Jadwal_Kelas_FK FOREIGN KEY
    (
     Kelas_Users_user_id,
     Kelas_kelas_id
    )
    REFERENCES Kelas
    (
     Users_user_id ,
     kelas_id
    )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION;

ALTER TABLE Jadwal
    ADD CONSTRAINT Jadwal_Matpel_FK FOREIGN KEY
    (
     Matpel_mapel_id
    )
    REFERENCES Matpel
    (
     mapel_id
    )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION;

ALTER TABLE Kelas
    ADD CONSTRAINT Kelas_Semester_FK FOREIGN KEY
    (
     Semester_semester_id
    )
    REFERENCES Semester
    (
     semester_id
    )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION;

ALTER TABLE Kelas
    ADD CONSTRAINT Kelas_Users_FK FOREIGN KEY
    (
     Users_user_id
    )
    REFERENCES Users
    (
     user_id
    )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION;

ALTER TABLE Materi
    ADD CONSTRAINT Materi_Kelas_FK FOREIGN KEY
    (
     Kelas_Users_user_id,
     Kelas_kelas_id
    )
    REFERENCES Kelas
    (
     Users_user_id ,
     kelas_id
    )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION;

ALTER TABLE Materi
    ADD CONSTRAINT Materi_Matpel_FK FOREIGN KEY
    (
     Matpel_mapel_id
    )
    REFERENCES Matpel
    (
     mapel_id
    )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION;

ALTER TABLE Nilai
    ADD CONSTRAINT Nilai_Matpel_FK FOREIGN KEY
    (
     Matpel_mapel_id
    )
    REFERENCES Matpel
    (
     mapel_id
    )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION;

ALTER TABLE Nilai
    ADD CONSTRAINT Nilai_Rapor_FK FOREIGN KEY
    (
     Rapor_rapor_id
    )
    REFERENCES Rapor
    (
     rapor_id
    )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION;

ALTER TABLE Pengumuman
    ADD CONSTRAINT Pengumuman_Users_FK FOREIGN KEY
    (
     Users_user_id
    )
    REFERENCES Users
    (
     user_id
    )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION;

ALTER TABLE Rapor
    ADD CONSTRAINT Rapor_Semester_FK FOREIGN KEY
    (
     Semester_semester_id
    )
    REFERENCES Semester
    (
     semester_id
    )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION;

ALTER TABLE Rapor
    ADD CONSTRAINT Rapor_Users_FK FOREIGN KEY
    (
     Users_user_id
    )
    REFERENCES Users
    (
     user_id
    )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION;

ALTER TABLE Tugas
    ADD CONSTRAINT Tugas_Kelas_FK FOREIGN KEY
    (
     Kelas_Users_user_id,
     Kelas_kelas_id
    )
    REFERENCES Kelas
    (
     Users_user_id ,
     kelas_id
    )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION;

ALTER TABLE Tugas
    ADD CONSTRAINT Tugas_Matpel_FK FOREIGN KEY
    (
     Matpel_mapel_id
    )
    REFERENCES Matpel
    (
     mapel_id
    )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION;

ALTER TABLE Ujian
    ADD CONSTRAINT Ujian_Kelas_FK FOREIGN KEY
    (
     Kelas_Users_user_id,
     Kelas_kelas_id
    )
    REFERENCES Kelas
    (
     Users_user_id ,
     kelas_id
    )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION;

ALTER TABLE Ujian
    ADD CONSTRAINT Ujian_Matpel_FK FOREIGN KEY
    (
     Matpel_mapel_id
    )
    REFERENCES Matpel
    (
     mapel_id
    )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION;

ALTER TABLE User_Log
    ADD CONSTRAINT User_Log_Users_FK FOREIGN KEY
    (
     Users_user_id
    )
    REFERENCES Users
    (
     user_id
    )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION;

ALTER TABLE Users
    ADD CONSTRAINT Users_Role_FK FOREIGN KEY
    (
     Role_role_id
    )
    REFERENCES Role
    (
     role_id
    )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION;

-- Foreign Keys for Student_Class_Enrollment
ALTER TABLE Student_Class_Enrollment
    ADD CONSTRAINT Student_Class_Enrollment_Users_FK FOREIGN KEY
    (
     Users_user_id
    )
    REFERENCES Users
    (
     user_id
    )
    ON DELETE CASCADE
    ON UPDATE CASCADE;

ALTER TABLE Student_Class_Enrollment
    ADD CONSTRAINT Student_Class_Enrollment_Kelas_FK FOREIGN KEY
    (
     Kelas_Users_user_id,
     Kelas_kelas_id
    )
    REFERENCES Kelas
    (
     Users_user_id ,
     kelas_id
    )
    ON DELETE CASCADE
    ON UPDATE CASCADE;

-- NEW TABLE: Student_Class_Enrollment
CREATE TABLE Student_Class_Enrollment
    (
     Users_user_id VARCHAR (7) NOT NULL ,
     Kelas_kelas_id SERIAL NOT NULL ,
     Kelas_Users_user_id VARCHAR (7) NOT NULL
    );

ALTER TABLE Student_Class_Enrollment ADD CONSTRAINT Student_Class_Enrollment_PK PRIMARY KEY (Users_user_id, Kelas_kelas_id, Kelas_Users_user_id);

-- Foreign Keys for Student_Class_Enrollment
ALTER TABLE Student_Class_Enrollment
    ADD CONSTRAINT Student_Class_Enrollment_Users_FK FOREIGN KEY
    (
     Users_user_id
    )
    REFERENCES Users
    (
     user_id
    )
    ON DELETE CASCADE
    ON UPDATE CASCADE;

ALTER TABLE Student_Class_Enrollment
    ADD CONSTRAINT Student_Class_Enrollment_Kelas_FK FOREIGN KEY
    (
     Kelas_Users_user_id,
     Kelas_kelas_id
    )
    REFERENCES Kelas
    (
     Users_user_id ,
     kelas_id
    )
    ON DELETE CASCADE
    ON UPDATE CASCADE;

ALTER TABLE pengumuman
ADD COLUMN waktu TIMESTAMP;